### ISSUE TITLE
OTX Nightly Build 2019-11-05 doesn't have an appimage

### ISSUE THREAD

**Issue by tbrimbo** [manongjohn/OTX#4]
### Issue Summary
Linux version of OTX Nightly Build 2019-11-05 doesn't have an appimage.

### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by manongjohn** [comment]
Thanks for reporting. Currently looking into it.

**Comment by manongjohn** [comment]
I've discovered the issue. I've manually compiled the linux version and created the appimage.  The OTX Nightly Build 2019-11-05 release has been updated.

Please check to see if it runs ok.

**Comment by tbrimbo** [comment]
Thanks for the update. That was quick.
