### ISSUE TITLE
OTX Nightly Build 2019-12-06 AppImage not launching

### ISSUE THREAD

**Issue by tbrimbo** [manongjohn/OTX#5]
Hi,

I am unable to launch OTX Nightly Build 2019-12-06 AppImage on Ubuntu 1804 or Manjaro Linux. Double clicking the file doesn't do anything. When I try to launch it via terminal, I get:

> /home/.../Downloads/OpenToonzPortable/OpenToonz.AppImage: symbol lookup error: /home/.../Downloads/OpenToonzPortable/OpenToonz.AppImage: undefined symbol: _ZN10TToolTimer10m_instanceE

Thanks.

**Comment by manongjohn** [comment]
Thanks for reporting. Will look into it as soon as I am able to.

**Comment by manongjohn** [comment]
I've fixed the AppImage and made sure it works this time. :)

I've updated the release.  Please let me know if you are still having trouble running it

**Comment by tbrimbo** [comment]
I launches fine. Thank you very much.
