### ISSUE TITLE
Smooth issue vector level

### ISSUE THREAD

**Issue by ghost** [manongjohn/OTX#6]
### Steps to Reproduce

Create a vector level and increase smooth option of the brush. In my case i used 20.

### Actual Results

Smooth doesn't work correctly
### System Information
* **OpenToonz Version**: 
last OTX
* **Operating System**:  win 10
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by manongjohn** [comment]
Can you check to see if this occurs in the latest official nightly or the Assistant Tool PR?  

I have a feeling its from the Assistant Tool changes, in which case it needs to be reported against that.

**Comment by ghost** [comment]
Indeed, this seems to be related to this PR. I encounter the same problems of slowness on the levels as what konero has already described. So I guess it's related.
