### ISSUE TITLE
Tablet pen pressure not working

### ISSUE THREAD

**Issue by tbrimbo** [manongjohn/OTX#7]
Tablet pen pressure is not working on Linux version of OTX 1.4 May 2020.

I made sure pressure box on tool options bar was ticked for toonz vector, toonz raster and raster levels. It doesn't work on any of them. Only on vector level, it starts thinner but then settles on a constant thickness. 

I tested the pressure on OTX 1.4 April 2020 and Morevna edition, it works on them.

**Device Information:**
 - OS: Manjaro Linux
 - OpenToonz Version: OTX 1.4 May 2020
 - GPU: GeForce GTX 1050/PCIe/SSE2
 - GPU Driver Version: 435.21

**Comment by manongjohn** [comment]
Thanks for reporting.  What type  of tablet do you have?

With the May version, I changed the build environment from Ubuntu 14.04 (Trusty) to 16.04 (Xenial) which is likely the cause, but not sure what part of the build might be causing that.

Not sure what I can do to fix this, yet, as I don't have a true linux machine.  I use a Linux VM for testing some stuff but I have trouble getting my tablet to work properly through the VM but I'll see what I can do.

**Comment by tbrimbo** [comment]
Tablet is a Huion 1060plus.
I just wanted to let you know but no worries if you can't fix it. There are still other versions of OpenToonz and they do the job. I can live without horizontal level strip.

**Comment by manongjohn** [comment]
I was able to confirm this issue and discovered what caused it.  I used the latest version of QT (5.14) which apparently has issues on Linux machines, I guess.  At any rate, I reverted my Linux builds back to use QT 5.9.7 and verified pressure was restored.

I'm currently rebuilding the may Linux version and will let you know when it's available.

**Comment by manongjohn** [comment]
New Linux version available.  Can be found here: [OTX 1.4 May 2020 (Linux Hotfix)](https://github.com/manongjohn/OTX/releases/tag/OTX-2020-05-13)

**Comment by tbrimbo** [comment]
Working great, thank you.
